[project]
name = "aws-python-lambda-layer"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "boto3>=1.37.23",
]

[dependency-groups]
dev = [
    "coverage>=7.7.1",
    "isort>=6.0.1",
    "pytest>=8.3.5",
    "ruff>=0.11.2",
]

[tool.ruff]
line-length=120

[tool.black]
line-length=120

[tool.ruff.lint]
extend-select = ["E501"]
